version: '3.9'

networks:
  default :
    name: 'pet_project_network'
    
volumes :
  PetProject-pg: 
  pgadmin:
  minio_data:
    
    
services:
  postgres:
    container_name: 'pet_postgres'
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    volumes:
      - PetProject-pg:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=PetProject
  
  pgadmin:
    container_name: 'pg_admin'
    image: 'dpage/pgadmin4:latest'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - '15435:80'
    volumes:
      - pgadmin:/var/lib/pgadmin
   
  minio:
    container_name: 'pet_minio'
    image: 'minio/minio'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ACCESS_KEY=minio_admin
      - MINIO_SECRET_KEY=minio_password
    volumes:
      - minio_data:/data
    command: server --console-address ":9001" /data
  
  seq:
    container_name: 'pet_seq'
    image: 'datalust/seq:latest'
    ports:
      - '5341:5341'
      - '8081:80'
    environment:
      - ACCEPT_EULA=Y
