// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PetProject.Discussions.Infrastructure.DbContexts;

#nullable disable

namespace PetProject.Discussions.Infrastructure.Migrations
{
    [DbContext(typeof(DiscussionsDbContext))]
    partial class DiscussionsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("discussions")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PetProject.Discussions.Domain.Aggregate.Discussion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("DeletionDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deletion_date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("RelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("relation_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_discussions");

                    b.ToTable("discussions", "discussions");
                });

            modelBuilder.Entity("PetProject.Discussions.Domain.Entity.Members", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("FirstMemberId")
                        .HasColumnType("bigint")
                        .HasColumnName("first_member_id");

                    b.Property<long>("SecondMemberId")
                        .HasColumnType("bigint")
                        .HasColumnName("second_member_id");

                    b.Property<Guid?>("discussion_id")
                        .HasColumnType("uuid")
                        .HasColumnName("discussion_id");

                    b.HasKey("Id")
                        .HasName("pk_members");

                    b.HasIndex("discussion_id")
                        .IsUnique()
                        .HasDatabaseName("ix_members_discussion_id");

                    b.ToTable("members", "discussions");
                });

            modelBuilder.Entity("PetProject.Discussions.Domain.Entity.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("boolean")
                        .HasColumnName("is_edited");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("discussion_id")
                        .HasColumnType("uuid")
                        .HasColumnName("discussion_id");

                    b.ComplexProperty<Dictionary<string, object>>("Text", "PetProject.Discussions.Domain.Entity.Message.Text#Text", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("text");
                        });

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.HasIndex("discussion_id")
                        .HasDatabaseName("ix_messages_discussion_id");

                    b.ToTable("messages", "discussions");
                });

            modelBuilder.Entity("PetProject.Discussions.Domain.Entity.Members", b =>
                {
                    b.HasOne("PetProject.Discussions.Domain.Aggregate.Discussion", null)
                        .WithOne("Members")
                        .HasForeignKey("PetProject.Discussions.Domain.Entity.Members", "discussion_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_members_discussions_discussion_id");
                });

            modelBuilder.Entity("PetProject.Discussions.Domain.Entity.Message", b =>
                {
                    b.HasOne("PetProject.Discussions.Domain.Aggregate.Discussion", null)
                        .WithMany("Messages")
                        .HasForeignKey("discussion_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_messages_discussions_discussion_id");
                });

            modelBuilder.Entity("PetProject.Discussions.Domain.Aggregate.Discussion", b =>
                {
                    b.Navigation("Members")
                        .IsRequired();

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
